version: '3.1'

services:
  web:
    image: nginx
    secrets:    
     - external-secret
     - file-secret

secrets:                        
  external-secret:
    external: true
  file-secret:
    file: file-secret.txt
