FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y nginx curl net-tools && \
    apt-get clean

COPY index.html /var/www/html/

RUN mkdir /opt/app
RUN echo 'hola amigos!' | cat >> hola.txt

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
