apiVersion: v1
kind: Pod
metadata:
  name: nginx-ping-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  - name: ping 
    image: nginx
    command:
      - "bin/sh"
      - "-c"
      - "sleep 10000"
